// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using YouTubeClone.Domain.Channels;
using YouTubeClone.Domain.Comments;
using YouTubeClone.Domain.Favorites;
using YouTubeClone.Domain.History;
using YouTubeClone.Domain.Playlists;
using YouTubeClone.Domain.Users;
using YouTubeClone.Domain.Videos;
using YouTubeClone.Infrastructure.Persistence;

#nullable disable

namespace YouTubeClone.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity<User>(entity =>
            {
                entity.ToTable("Users");
                entity.HasKey(user => user.Id);
                entity.Property(user => user.Email).HasMaxLength(256).IsRequired();
                entity.Property(user => user.UserName).HasMaxLength(64).IsRequired();
                entity.Property(user => user.DisplayName).HasMaxLength(100).IsRequired();
                entity.Property(user => user.Bio).HasMaxLength(240).IsRequired();
                entity.Property(user => user.AvatarPath).HasMaxLength(512);
                entity.Property(user => user.ThemeId).HasMaxLength(64);
                entity.Property(user => user.PasswordHash).HasMaxLength(512).IsRequired();
                entity.Property(user => user.CreatedAt);
                entity.HasIndex(user => user.Email).IsUnique();
                entity.HasIndex(user => user.UserName).IsUnique();
            });

            modelBuilder.Entity<RefreshToken>(entity =>
            {
                entity.ToTable("RefreshTokens");
                entity.HasKey(token => token.Id);
                entity.Property(token => token.TokenHash).HasMaxLength(128).IsRequired();
                entity.Property(token => token.ExpiresAt);
                entity.Property(token => token.RevokedAt);
                entity.HasIndex(token => token.TokenHash).IsUnique();
                entity.HasIndex(token => token.UserId);
                entity.HasOne(token => token.User)
                    .WithMany(user => user.RefreshTokens)
                    .HasForeignKey(token => token.UserId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity<Channel>(entity =>
            {
                entity.ToTable("Channels");
                entity.HasKey(channel => channel.Id);
                entity.Property(channel => channel.Name).HasMaxLength(100).IsRequired();
                entity.Property(channel => channel.Handle).HasMaxLength(64).IsRequired();
                entity.Property(channel => channel.Description).HasMaxLength(1000).IsRequired();
                entity.Property(channel => channel.AvatarPath).HasMaxLength(512);
                entity.Property(channel => channel.BannerPath).HasMaxLength(512);
                entity.Property(channel => channel.CreatedAt);
                entity.HasIndex(channel => channel.Handle).IsUnique();
                entity.HasIndex(channel => channel.OwnerId).IsUnique();
                entity.HasOne<User>()
                    .WithOne()
                    .HasForeignKey<Channel>(channel => channel.OwnerId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity<Subscription>(entity =>
            {
                entity.ToTable("Subscriptions");
                entity.HasKey(subscription => new
                {
                    subscription.SubscriberId,
                    subscription.ChannelId
                });
                entity.Property(subscription => subscription.CreatedAt);
                entity.HasIndex(subscription => subscription.ChannelId);
                entity.HasOne<User>()
                    .WithMany()
                    .HasForeignKey(subscription => subscription.SubscriberId)
                    .OnDelete(DeleteBehavior.NoAction);
                entity.HasOne(subscription => subscription.Channel)
                    .WithMany()
                    .HasForeignKey(subscription => subscription.ChannelId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity<Comment>(entity =>
            {
                entity.ToTable("Comments");
                entity.HasKey(comment => comment.Id);
                entity.Property(comment => comment.Text).HasMaxLength(500).IsRequired();
                entity.Property(comment => comment.CreatedAt);
                entity.HasIndex(comment => comment.VideoId);
                entity.HasIndex(comment => comment.AuthorId);
                entity.HasIndex(comment => comment.ParentCommentId);
            });

            modelBuilder.Entity<CommentReaction>(entity =>
            {
                entity.ToTable("CommentReactions");
                entity.HasKey(reaction => new
                {
                    reaction.CommentId,
                    reaction.UserId
                });
                entity.Property(reaction => reaction.Kind).IsRequired();
                entity.Property(reaction => reaction.UpdatedAt);
                entity.HasOne(reaction => reaction.Comment)
                    .WithMany(comment => comment.Reactions)
                    .HasForeignKey(reaction => reaction.CommentId)
                    .OnDelete(DeleteBehavior.Cascade);
                entity.HasIndex(reaction => reaction.UserId);
            });

            modelBuilder.Entity<Playlist>(entity =>
            {
                entity.ToTable("Playlists");
                entity.HasKey(playlist => playlist.Id);
                entity.Property(playlist => playlist.Title).HasMaxLength(80).IsRequired();
                entity.Property(playlist => playlist.Description).HasMaxLength(300).IsRequired();
                entity.Property(playlist => playlist.CreatedAt);
                entity.Property(playlist => playlist.UpdatedAt);
                entity.HasIndex(playlist => playlist.OwnerId);
                entity.HasOne<User>()
                    .WithMany()
                    .HasForeignKey(playlist => playlist.OwnerId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity<PlaylistVideo>(entity =>
            {
                entity.ToTable("PlaylistVideos");
                entity.HasKey(item => new
                {
                    item.PlaylistId,
                    item.VideoId
                });
                entity.Property(item => item.AddedAt);
                entity.HasOne(item => item.Playlist)
                    .WithMany(playlist => playlist.Videos)
                    .HasForeignKey(item => item.PlaylistId)
                    .OnDelete(DeleteBehavior.Cascade);
                entity.HasIndex(item => item.VideoId);
            });

            modelBuilder.Entity<Video>(entity =>
            {
                entity.ToTable("Videos");
                entity.HasKey(video => video.Id);
                entity.Property(video => video.ChannelName).HasMaxLength(100).IsRequired();
                entity.Property(video => video.ChannelAvatarPath).HasMaxLength(512);
                entity.Property(video => video.Category).HasMaxLength(100);
                entity.Property(video => video.CategorySlug).HasMaxLength(100);
                entity.Property(video => video.Title).HasMaxLength(200).IsRequired();
                entity.Property(video => video.Description).HasMaxLength(5000);
                entity.Property(video => video.VideoPath).HasMaxLength(512).IsRequired();
                entity.Property(video => video.ThumbnailPath).HasMaxLength(512);
                entity.Property(video => video.DurationSeconds);
                entity.Property(video => video.ViewCount);
                entity.Property(video => video.Visibility).HasMaxLength(32).IsRequired();
                entity.HasIndex(video => video.ChannelId);
                entity.HasIndex(video => video.CategorySlug);
                entity.HasIndex(video => video.PublishedAt);
            });

            modelBuilder.Entity<WatchHistoryEntry>(entity =>
            {
                entity.ToTable("WatchHistoryEntries");
                entity.HasKey(entry => new
                {
                    entry.UserId,
                    entry.VideoId
                });
                entity.Property(entry => entry.ProgressSeconds);
                entity.Property(entry => entry.Completed);
                entity.HasOne<User>()
                    .WithMany()
                    .HasForeignKey(entry => entry.UserId)
                    .OnDelete(DeleteBehavior.Cascade);
                entity.HasIndex(entry => new
                {
                    entry.UserId,
                    entry.LastWatchedAt
                });
            });

            modelBuilder.Entity<WatchHistoryPreference>(entity =>
            {
                entity.ToTable("WatchHistoryPreferences");
                entity.HasKey(preference => preference.UserId);
                entity.Property(preference => preference.IsPaused);
                entity.HasOne<User>()
                    .WithOne()
                    .HasForeignKey<WatchHistoryPreference>(preference => preference.UserId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity<FavoriteEntry>(entity =>
            {
                entity.ToTable("FavoriteEntries");
                entity.HasKey(entry => new
                {
                    entry.UserId,
                    entry.VideoId
                });
                entity.HasOne<User>()
                    .WithMany()
                    .HasForeignKey(entry => entry.UserId)
                    .OnDelete(DeleteBehavior.Cascade);
                entity.HasIndex(entry => new
                {
                    entry.UserId,
                    entry.CreatedAt
                });
            });
#pragma warning restore 612, 618
        }
    }
}
